name = "gleam_cowboy_websockets"
version = "0.1.0"

licences = ["MIT"]
description = "An expermimental Gleam library for playing with Cowboy websockets"
repository = { type = "github", user = "vstreame", repo = "gleam_cowboy_websockets" }

[dependencies]
gleam_stdlib = "~> 0.20"
gleam_http = "~> 3.0"
gleam_otp = "~> 0.3"
cowboy = "~> 2.9"
gleam_erlang = "~> 0.9"

[dev-dependencies]
gleeunit = "~> 0.6"
gun = "> 1.3.0 and < 3.0.0"
